//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.19 at 05:28:17 PM CEST 
//


package org.xmlspif.spif;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for securityCategoryTag complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="securityCategoryTag">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.xmlspif.org/spif}tagCategory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}markingQualifier" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tagType" use="required" type="{http://www.xmlspif.org/spif}tagType" />
 *       &lt;attribute name="enumType" type="{http://www.xmlspif.org/spif}enumType" />
 *       &lt;attribute name="tag7Encoding" type="{http://www.xmlspif.org/spif}tag7Encoding" />
 *       &lt;attribute name="singleSelection" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="maxSelection" type="{http://www.xmlspif.org/spif}selection" default="unbounded" />
 *       &lt;attribute name="minSelection" type="{http://www.xmlspif.org/spif}selection" default="unbounded" />
 *       &lt;anyAttribute/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securityCategoryTag", propOrder = {
    "tagCategory",
    "markingQualifier"
})
public class SecurityCategoryTag {

    protected List<TagCategory> tagCategory;
    protected List<MarkingQualifier> markingQualifier;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "tagType", required = true)
    protected TagType tagType;
    @XmlAttribute(name = "enumType")
    protected EnumType enumType;
    @XmlAttribute(name = "tag7Encoding")
    protected Tag7Encoding tag7Encoding;
    @XmlAttribute(name = "singleSelection")
    protected Boolean singleSelection;
    @XmlAttribute(name = "maxSelection")
    protected String maxSelection;
    @XmlAttribute(name = "minSelection")
    protected String minSelection;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the tagCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TagCategory }
     * 
     * 
     */
    public List<TagCategory> getTagCategory() {
        if (tagCategory == null) {
            tagCategory = new ArrayList<TagCategory>();
        }
        return this.tagCategory;
    }

    /**
     * Gets the value of the markingQualifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markingQualifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkingQualifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarkingQualifier }
     * 
     * 
     */
    public List<MarkingQualifier> getMarkingQualifier() {
        if (markingQualifier == null) {
            markingQualifier = new ArrayList<MarkingQualifier>();
        }
        return this.markingQualifier;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the tagType property.
     * 
     * @return
     *     possible object is
     *     {@link TagType }
     *     
     */
    public TagType getTagType() {
        return tagType;
    }

    /**
     * Sets the value of the tagType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagType }
     *     
     */
    public void setTagType(TagType value) {
        this.tagType = value;
    }

    /**
     * Gets the value of the enumType property.
     * 
     * @return
     *     possible object is
     *     {@link EnumType }
     *     
     */
    public EnumType getEnumType() {
        return enumType;
    }

    /**
     * Sets the value of the enumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumType }
     *     
     */
    public void setEnumType(EnumType value) {
        this.enumType = value;
    }

    /**
     * Gets the value of the tag7Encoding property.
     * 
     * @return
     *     possible object is
     *     {@link Tag7Encoding }
     *     
     */
    public Tag7Encoding getTag7Encoding() {
        return tag7Encoding;
    }

    /**
     * Sets the value of the tag7Encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tag7Encoding }
     *     
     */
    public void setTag7Encoding(Tag7Encoding value) {
        this.tag7Encoding = value;
    }

    /**
     * Gets the value of the singleSelection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSingleSelection() {
        if (singleSelection == null) {
            return false;
        } else {
            return singleSelection;
        }
    }

    /**
     * Sets the value of the singleSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSingleSelection(Boolean value) {
        this.singleSelection = value;
    }

    /**
     * Gets the value of the maxSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxSelection() {
        if (maxSelection == null) {
            return "unbounded";
        } else {
            return maxSelection;
        }
    }

    /**
     * Sets the value of the maxSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxSelection(String value) {
        this.maxSelection = value;
    }

    /**
     * Gets the value of the minSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinSelection() {
        if (minSelection == null) {
            return "unbounded";
        } else {
            return minSelection;
        }
    }

    /**
     * Sets the value of the minSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinSelection(String value) {
        this.minSelection = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
