//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.19 at 05:28:17 PM CEST 
//


package org.xmlspif.spif;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.xmlspif.org/spif}defaultSecurityPolicyId" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}securityPolicyId"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}updateInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}securityClassifications"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}securityCategoryTagSets" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}privacyMarks" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}equivalentPolicies" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}markingData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}markingQualifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.xmlspif.org/spif}extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.xmlspif.org/spif}validity"/>
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.xmlspif.org/spif}version" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" />
 *       &lt;attribute name="creationDate" use="required" type="{http://www.xmlspif.org/spif}genTime" />
 *       &lt;attribute name="originatorDN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keyIdentifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="privilegeId" use="required" type="{http://www.xmlspif.org/spif}oid" />
 *       &lt;attribute name="rbacId" use="required" type="{http://www.xmlspif.org/spif}oid" />
 *       &lt;attribute name="userRefURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="docRefURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultSecurityPolicyId",
    "securityPolicyId",
    "updateInfo",
    "securityClassifications",
    "securityCategoryTagSets",
    "privacyMarks",
    "equivalentPolicies",
    "markingData",
    "markingQualifier",
    "extensions"
})
@XmlRootElement(name = "SPIF")
public class SPIF {

    protected ObjectIdData defaultSecurityPolicyId;
    @XmlElement(required = true)
    protected ObjectIdData securityPolicyId;
    protected UpdateInfo updateInfo;
    @XmlElement(required = true)
    protected SecurityClassifications securityClassifications;
    protected SecurityCategoryTagSets securityCategoryTagSets;
    protected PrivacyMarks privacyMarks;
    protected EquivalentPolicies equivalentPolicies;
    protected List<MarkingData> markingData;
    protected List<MarkingQualifier> markingQualifier;
    protected Extensions extensions;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;
    @XmlAttribute(name = "version")
    protected BigInteger version;
    @XmlAttribute(name = "creationDate", required = true)
    protected String creationDate;
    @XmlAttribute(name = "originatorDN", required = true)
    protected String originatorDN;
    @XmlAttribute(name = "keyIdentifier", required = true)
    protected String keyIdentifier;
    @XmlAttribute(name = "privilegeId", required = true)
    protected String privilegeId;
    @XmlAttribute(name = "rbacId", required = true)
    protected String rbacId;
    @XmlAttribute(name = "userRefURI")
    @XmlSchemaType(name = "anyURI")
    protected String userRefURI;
    @XmlAttribute(name = "docRefURI")
    @XmlSchemaType(name = "anyURI")
    protected String docRefURI;
    @XmlAttribute(name = "notBefore")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar notBefore;
    @XmlAttribute(name = "notAfter")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar notAfter;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the defaultSecurityPolicyId property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectIdData }
     *     
     */
    public ObjectIdData getDefaultSecurityPolicyId() {
        return defaultSecurityPolicyId;
    }

    /**
     * Sets the value of the defaultSecurityPolicyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectIdData }
     *     
     */
    public void setDefaultSecurityPolicyId(ObjectIdData value) {
        this.defaultSecurityPolicyId = value;
    }

    /**
     * Gets the value of the securityPolicyId property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectIdData }
     *     
     */
    public ObjectIdData getSecurityPolicyId() {
        return securityPolicyId;
    }

    /**
     * Sets the value of the securityPolicyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectIdData }
     *     
     */
    public void setSecurityPolicyId(ObjectIdData value) {
        this.securityPolicyId = value;
    }

    /**
     * Gets the value of the updateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateInfo }
     *     
     */
    public UpdateInfo getUpdateInfo() {
        return updateInfo;
    }

    /**
     * Sets the value of the updateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateInfo }
     *     
     */
    public void setUpdateInfo(UpdateInfo value) {
        this.updateInfo = value;
    }

    /**
     * Gets the value of the securityClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityClassifications }
     *     
     */
    public SecurityClassifications getSecurityClassifications() {
        return securityClassifications;
    }

    /**
     * Sets the value of the securityClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityClassifications }
     *     
     */
    public void setSecurityClassifications(SecurityClassifications value) {
        this.securityClassifications = value;
    }

    /**
     * Gets the value of the securityCategoryTagSets property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityCategoryTagSets }
     *     
     */
    public SecurityCategoryTagSets getSecurityCategoryTagSets() {
        return securityCategoryTagSets;
    }

    /**
     * Sets the value of the securityCategoryTagSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityCategoryTagSets }
     *     
     */
    public void setSecurityCategoryTagSets(SecurityCategoryTagSets value) {
        this.securityCategoryTagSets = value;
    }

    /**
     * Gets the value of the privacyMarks property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyMarks }
     *     
     */
    public PrivacyMarks getPrivacyMarks() {
        return privacyMarks;
    }

    /**
     * Sets the value of the privacyMarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyMarks }
     *     
     */
    public void setPrivacyMarks(PrivacyMarks value) {
        this.privacyMarks = value;
    }

    /**
     * Gets the value of the equivalentPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link EquivalentPolicies }
     *     
     */
    public EquivalentPolicies getEquivalentPolicies() {
        return equivalentPolicies;
    }

    /**
     * Sets the value of the equivalentPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquivalentPolicies }
     *     
     */
    public void setEquivalentPolicies(EquivalentPolicies value) {
        this.equivalentPolicies = value;
    }

    /**
     * Gets the value of the markingData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markingData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkingData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarkingData }
     * 
     * 
     */
    public List<MarkingData> getMarkingData() {
        if (markingData == null) {
            markingData = new ArrayList<MarkingData>();
        }
        return this.markingData;
    }

    /**
     * Gets the value of the markingQualifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markingQualifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkingQualifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarkingQualifier }
     * 
     * 
     */
    public List<MarkingQualifier> getMarkingQualifier() {
        if (markingQualifier == null) {
            markingQualifier = new ArrayList<MarkingQualifier>();
        }
        return this.markingQualifier;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        if (version == null) {
            return new BigInteger("1");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the originatorDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorDN() {
        return originatorDN;
    }

    /**
     * Sets the value of the originatorDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorDN(String value) {
        this.originatorDN = value;
    }

    /**
     * Gets the value of the keyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyIdentifier() {
        return keyIdentifier;
    }

    /**
     * Sets the value of the keyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyIdentifier(String value) {
        this.keyIdentifier = value;
    }

    /**
     * Gets the value of the privilegeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivilegeId() {
        return privilegeId;
    }

    /**
     * Sets the value of the privilegeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivilegeId(String value) {
        this.privilegeId = value;
    }

    /**
     * Gets the value of the rbacId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRbacId() {
        return rbacId;
    }

    /**
     * Sets the value of the rbacId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRbacId(String value) {
        this.rbacId = value;
    }

    /**
     * Gets the value of the userRefURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRefURI() {
        return userRefURI;
    }

    /**
     * Sets the value of the userRefURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRefURI(String value) {
        this.userRefURI = value;
    }

    /**
     * Gets the value of the docRefURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocRefURI() {
        return docRefURI;
    }

    /**
     * Sets the value of the docRefURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocRefURI(String value) {
        this.docRefURI = value;
    }

    /**
     * Gets the value of the notBefore property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNotBefore() {
        return notBefore;
    }

    /**
     * Sets the value of the notBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNotBefore(XMLGregorianCalendar value) {
        this.notBefore = value;
    }

    /**
     * Gets the value of the notAfter property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNotAfter() {
        return notAfter;
    }

    /**
     * Sets the value of the notAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNotAfter(XMLGregorianCalendar value) {
        this.notAfter = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
