//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.19 at 05:28:17 PM CEST 
//


package org.xmlspif.spif;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tag7Encoding.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tag7Encoding">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="bitSetAttributes"/>
 *     &lt;enumeration value="securityAttributes"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tag7Encoding")
@XmlEnum
public enum Tag7Encoding {

    @XmlEnumValue("bitSetAttributes")
    BIT_SET_ATTRIBUTES("bitSetAttributes"),
    @XmlEnumValue("securityAttributes")
    SECURITY_ATTRIBUTES("securityAttributes");
    private final String value;

    Tag7Encoding(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Tag7Encoding fromValue(String v) {
        for (Tag7Encoding c: Tag7Encoding.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
