//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.01 at 12:18:02 PM CEST 
//


package org.xmlspif.spif;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xmlspif.spif package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequiredCategory_QNAME = new QName("http://www.xmlspif.org/spif", "requiredCategory");
    private final static QName _PrivacyMark_QNAME = new QName("http://www.xmlspif.org/spif", "privacyMark");
    private final static QName _EquivalentSecurityCategoryTagSet_QNAME = new QName("http://www.xmlspif.org/spif", "equivalentSecurityCategoryTagSet");
    private final static QName _ExcludedCategory_QNAME = new QName("http://www.xmlspif.org/spif", "excludedCategory");
    private final static QName _TagCategory_QNAME = new QName("http://www.xmlspif.org/spif", "tagCategory");
    private final static QName _PrivacyMarks_QNAME = new QName("http://www.xmlspif.org/spif", "privacyMarks");
    private final static QName _DefaultSecurityPolicyId_QNAME = new QName("http://www.xmlspif.org/spif", "defaultSecurityPolicyId");
    private final static QName _SecurityClassification_QNAME = new QName("http://www.xmlspif.org/spif", "securityClassification");
    private final static QName _EquivalentSecCategoryTag_QNAME = new QName("http://www.xmlspif.org/spif", "equivalentSecCategoryTag");
    private final static QName _SecurityClassifications_QNAME = new QName("http://www.xmlspif.org/spif", "securityClassifications");
    private final static QName _CategoryGroup_QNAME = new QName("http://www.xmlspif.org/spif", "categoryGroup");
    private final static QName _MarkingQualifier_QNAME = new QName("http://www.xmlspif.org/spif", "markingQualifier");
    private final static QName _Extensions_QNAME = new QName("http://www.xmlspif.org/spif", "extensions");
    private final static QName _ExcludedClass_QNAME = new QName("http://www.xmlspif.org/spif", "excludedClass");
    private final static QName _SecurityPolicyId_QNAME = new QName("http://www.xmlspif.org/spif", "securityPolicyId");
    private final static QName _Qualifier_QNAME = new QName("http://www.xmlspif.org/spif", "qualifier");
    private final static QName _SecurityCategoryTagSet_QNAME = new QName("http://www.xmlspif.org/spif", "securityCategoryTagSet");
    private final static QName _EquivalentClassification_QNAME = new QName("http://www.xmlspif.org/spif", "equivalentClassification");
    private final static QName _UpdateInfo_QNAME = new QName("http://www.xmlspif.org/spif", "updateInfo");
    private final static QName _Code_QNAME = new QName("http://www.xmlspif.org/spif", "code");
    private final static QName _MarkingData_QNAME = new QName("http://www.xmlspif.org/spif", "markingData");
    private final static QName _EquivalentPolicies_QNAME = new QName("http://www.xmlspif.org/spif", "equivalentPolicies");
    private final static QName _EquivalentPolicy_QNAME = new QName("http://www.xmlspif.org/spif", "equivalentPolicy");
    private final static QName _SecurityCategoryTag_QNAME = new QName("http://www.xmlspif.org/spif", "securityCategoryTag");
    private final static QName _SecurityCategoryTagSets_QNAME = new QName("http://www.xmlspif.org/spif", "securityCategoryTagSets");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xmlspif.spif
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateInfo }
     * 
     */
    public UpdateInfo createUpdateInfo() {
        return new UpdateInfo();
    }

    /**
     * Create an instance of {@link MarkingData }
     * 
     */
    public MarkingData createMarkingData() {
        return new MarkingData();
    }

    /**
     * Create an instance of {@link SecurityCategoryTagSet }
     * 
     */
    public SecurityCategoryTagSet createSecurityCategoryTagSet() {
        return new SecurityCategoryTagSet();
    }

    /**
     * Create an instance of {@link EquivalentClassification }
     * 
     */
    public EquivalentClassification createEquivalentClassification() {
        return new EquivalentClassification();
    }

    /**
     * Create an instance of {@link EquivalentPolicy }
     * 
     */
    public EquivalentPolicy createEquivalentPolicy() {
        return new EquivalentPolicy();
    }

    /**
     * Create an instance of {@link SecurityCategoryTag }
     * 
     */
    public SecurityCategoryTag createSecurityCategoryTag() {
        return new SecurityCategoryTag();
    }

    /**
     * Create an instance of {@link SecurityCategoryTagSets }
     * 
     */
    public SecurityCategoryTagSets createSecurityCategoryTagSets() {
        return new SecurityCategoryTagSets();
    }

    /**
     * Create an instance of {@link EquivalentPolicies }
     * 
     */
    public EquivalentPolicies createEquivalentPolicies() {
        return new EquivalentPolicies();
    }

    /**
     * Create an instance of {@link SPIF }
     * 
     */
    public SPIF createSPIF() {
        return new SPIF();
    }

    /**
     * Create an instance of {@link ObjectIdData }
     * 
     */
    public ObjectIdData createObjectIdData() {
        return new ObjectIdData();
    }

    /**
     * Create an instance of {@link SecurityClassifications }
     * 
     */
    public SecurityClassifications createSecurityClassifications() {
        return new SecurityClassifications();
    }

    /**
     * Create an instance of {@link PrivacyMarks }
     * 
     */
    public PrivacyMarks createPrivacyMarks() {
        return new PrivacyMarks();
    }

    /**
     * Create an instance of {@link MarkingQualifier }
     * 
     */
    public MarkingQualifier createMarkingQualifier() {
        return new MarkingQualifier();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link OptionalCategoryData }
     * 
     */
    public OptionalCategoryData createOptionalCategoryData() {
        return new OptionalCategoryData();
    }

    /**
     * Create an instance of {@link TagCategory }
     * 
     */
    public TagCategory createTagCategory() {
        return new TagCategory();
    }

    /**
     * Create an instance of {@link SecurityClassification }
     * 
     */
    public SecurityClassification createSecurityClassification() {
        return new SecurityClassification();
    }

    /**
     * Create an instance of {@link OptionalCategoryGroup }
     * 
     */
    public OptionalCategoryGroup createOptionalCategoryGroup() {
        return new OptionalCategoryGroup();
    }

    /**
     * Create an instance of {@link PrivacyMark }
     * 
     */
    public PrivacyMark createPrivacyMark() {
        return new PrivacyMark();
    }

    /**
     * Create an instance of {@link EquivalentSecurityCategoryTagSet }
     * 
     */
    public EquivalentSecurityCategoryTagSet createEquivalentSecurityCategoryTagSet() {
        return new EquivalentSecurityCategoryTagSet();
    }

    /**
     * Create an instance of {@link Qualifier }
     * 
     */
    public Qualifier createQualifier() {
        return new Qualifier();
    }

    /**
     * Create an instance of {@link EquivalentSecCategoryTag }
     * 
     */
    public EquivalentSecCategoryTag createEquivalentSecCategoryTag() {
        return new EquivalentSecCategoryTag();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalCategoryGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "requiredCategory")
    public JAXBElement<OptionalCategoryGroup> createRequiredCategory(OptionalCategoryGroup value) {
        return new JAXBElement<OptionalCategoryGroup>(_RequiredCategory_QNAME, OptionalCategoryGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivacyMark }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "privacyMark")
    public JAXBElement<PrivacyMark> createPrivacyMark(PrivacyMark value) {
        return new JAXBElement<PrivacyMark>(_PrivacyMark_QNAME, PrivacyMark.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquivalentSecurityCategoryTagSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "equivalentSecurityCategoryTagSet")
    public JAXBElement<EquivalentSecurityCategoryTagSet> createEquivalentSecurityCategoryTagSet(EquivalentSecurityCategoryTagSet value) {
        return new JAXBElement<EquivalentSecurityCategoryTagSet>(_EquivalentSecurityCategoryTagSet_QNAME, EquivalentSecurityCategoryTagSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalCategoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "excludedCategory")
    public JAXBElement<OptionalCategoryData> createExcludedCategory(OptionalCategoryData value) {
        return new JAXBElement<OptionalCategoryData>(_ExcludedCategory_QNAME, OptionalCategoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TagCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "tagCategory")
    public JAXBElement<TagCategory> createTagCategory(TagCategory value) {
        return new JAXBElement<TagCategory>(_TagCategory_QNAME, TagCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivacyMarks }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "privacyMarks")
    public JAXBElement<PrivacyMarks> createPrivacyMarks(PrivacyMarks value) {
        return new JAXBElement<PrivacyMarks>(_PrivacyMarks_QNAME, PrivacyMarks.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectIdData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "defaultSecurityPolicyId")
    public JAXBElement<ObjectIdData> createDefaultSecurityPolicyId(ObjectIdData value) {
        return new JAXBElement<ObjectIdData>(_DefaultSecurityPolicyId_QNAME, ObjectIdData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityClassification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "securityClassification")
    public JAXBElement<SecurityClassification> createSecurityClassification(SecurityClassification value) {
        return new JAXBElement<SecurityClassification>(_SecurityClassification_QNAME, SecurityClassification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquivalentSecCategoryTag }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "equivalentSecCategoryTag")
    public JAXBElement<EquivalentSecCategoryTag> createEquivalentSecCategoryTag(EquivalentSecCategoryTag value) {
        return new JAXBElement<EquivalentSecCategoryTag>(_EquivalentSecCategoryTag_QNAME, EquivalentSecCategoryTag.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityClassifications }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "securityClassifications")
    public JAXBElement<SecurityClassifications> createSecurityClassifications(SecurityClassifications value) {
        return new JAXBElement<SecurityClassifications>(_SecurityClassifications_QNAME, SecurityClassifications.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalCategoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "categoryGroup")
    public JAXBElement<OptionalCategoryData> createCategoryGroup(OptionalCategoryData value) {
        return new JAXBElement<OptionalCategoryData>(_CategoryGroup_QNAME, OptionalCategoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkingQualifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "markingQualifier")
    public JAXBElement<MarkingQualifier> createMarkingQualifier(MarkingQualifier value) {
        return new JAXBElement<MarkingQualifier>(_MarkingQualifier_QNAME, MarkingQualifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Extensions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "extensions")
    public JAXBElement<Extensions> createExtensions(Extensions value) {
        return new JAXBElement<Extensions>(_Extensions_QNAME, Extensions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "excludedClass")
    public JAXBElement<String> createExcludedClass(String value) {
        return new JAXBElement<String>(_ExcludedClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectIdData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "securityPolicyId")
    public JAXBElement<ObjectIdData> createSecurityPolicyId(ObjectIdData value) {
        return new JAXBElement<ObjectIdData>(_SecurityPolicyId_QNAME, ObjectIdData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Qualifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "qualifier")
    public JAXBElement<Qualifier> createQualifier(Qualifier value) {
        return new JAXBElement<Qualifier>(_Qualifier_QNAME, Qualifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityCategoryTagSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "securityCategoryTagSet")
    public JAXBElement<SecurityCategoryTagSet> createSecurityCategoryTagSet(SecurityCategoryTagSet value) {
        return new JAXBElement<SecurityCategoryTagSet>(_SecurityCategoryTagSet_QNAME, SecurityCategoryTagSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquivalentClassification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "equivalentClassification")
    public JAXBElement<EquivalentClassification> createEquivalentClassification(EquivalentClassification value) {
        return new JAXBElement<EquivalentClassification>(_EquivalentClassification_QNAME, EquivalentClassification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "updateInfo")
    public JAXBElement<UpdateInfo> createUpdateInfo(UpdateInfo value) {
        return new JAXBElement<UpdateInfo>(_UpdateInfo_QNAME, UpdateInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkingCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "code")
    public JAXBElement<MarkingCode> createCode(MarkingCode value) {
        return new JAXBElement<MarkingCode>(_Code_QNAME, MarkingCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkingData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "markingData")
    public JAXBElement<MarkingData> createMarkingData(MarkingData value) {
        return new JAXBElement<MarkingData>(_MarkingData_QNAME, MarkingData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquivalentPolicies }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "equivalentPolicies")
    public JAXBElement<EquivalentPolicies> createEquivalentPolicies(EquivalentPolicies value) {
        return new JAXBElement<EquivalentPolicies>(_EquivalentPolicies_QNAME, EquivalentPolicies.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquivalentPolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "equivalentPolicy")
    public JAXBElement<EquivalentPolicy> createEquivalentPolicy(EquivalentPolicy value) {
        return new JAXBElement<EquivalentPolicy>(_EquivalentPolicy_QNAME, EquivalentPolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityCategoryTag }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "securityCategoryTag")
    public JAXBElement<SecurityCategoryTag> createSecurityCategoryTag(SecurityCategoryTag value) {
        return new JAXBElement<SecurityCategoryTag>(_SecurityCategoryTag_QNAME, SecurityCategoryTag.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityCategoryTagSets }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xmlspif.org/spif", name = "securityCategoryTagSets")
    public JAXBElement<SecurityCategoryTagSets> createSecurityCategoryTagSets(SecurityCategoryTagSets value) {
        return new JAXBElement<SecurityCategoryTagSets>(_SecurityCategoryTagSets_QNAME, SecurityCategoryTagSets.class, null, value);
    }

}
